[pytest]
testpaths = tests
filterwarnings =
    ignore::UserWarning:jieba.*:
    ignore::DeprecationWarning:.*SwigPyPacked.*:
    ignore::DeprecationWarning:.*SwigPyObject.*:
    ignore::DeprecationWarning:.*swigvarlink.*:
